name: Publish Docker images to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Build and push Docker image 1.0
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-1-0
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/custom-nginx:1.0

      - name: Build and push Docker image 1.1
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-1-1
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/custom-nginx:1.1

      - name: Build and push Docker image 1.2
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile-1-2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/custom-nginx:1.2
